apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-deployment
  labels:
    app: hellok8s
spec:
  replicas: {{ .Values.deployments.replicas }}
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - name: hellok8s
        image: {{ .Values.deployments.image.repository }}:{{ .Values.deployments.image.tag }}
        ports:
        - containerPort: {{ .Values.deployments.port }}