apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
spec:
  type: {{ .Values.service.type }} 
  selector:
    app: hellok8s
  ports:
  - port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.targetPort }}